<?xml version="1.0"?>

<st-source>
<time-stamp>From VisualWorks®, 7.9.1 of 18 October 2012 on 31 October 2016 at 5:50:16 PM</time-stamp>


<component-created>
<name>Kernel-TExtensions</name> <type>package</type>
</component-created><!-- Package Kernel-TExtensions* -->


<component-property>
<name>Kernel-TExtensions</name> <type>package</type>
<property>packageName</property> <value>'Kernel-TExtensions'</value>
</component-property>

<methods>
<class-id>Core.UndefinedObject class</class-id> <category>accessing</category>

<body package="Kernel-TExtensions" selector="methodsFor:stamp:">methodsFor: aString stamp: aStamp	^self methodsFor: aString</body>
</methods>


<methods>
<class-id>Core.ClassDescription</class-id> <category>accessing</category>

<body package="Kernel-TExtensions" selector="methodsFor:stamp:">methodsFor: aString stamp: aStamp	^self methodsFor: aString</body>
</methods>



</st-source>
